services:
  n8n:
    image: n8nio/n8n:latest
    ports: 
      - "5678:5678"
    environment:
      - WEBHOOK_URL=https://fhr.rifqinm.web.id/
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
